name: Deploy to EC2

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend
        run: |
          docker build -t basit/hello-backend:latest ./backend
          docker push basit/hello-backend:latest

      - name: Build Frontend
        run: |
          docker build -t basit/hello-frontend:latest ./frontend
          docker push basit/hello-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd app
            docker-compose pull
            docker-compose up -d
